apiVersion: v1
kind: Service
metadata:
  name: email-service-svc
spec:
  selector:
    app: email-service # <--- This "points" the Service to our Pods
  ports:
    - protocol: TCP
      port: 80 # <--- The port other apps inside the cluster will use
      targetPort: 8080 # <--- The port our Python app is actually listening on
  type: ClusterIP # <--- Means this is only accessible "inside" the cluster